version: '3'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - PYTHONPATH=api
    ports:
      - '8000:8000'
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
